/*
 * AI Safety Glossary — onboarding page behaviors.
 *
 * Progressive enhancement for the desktop-only install/onboarding page. The
 * page markup is owned by onboarding.html; this script only wires behavior onto
 * the shared-contract element IDs:
 *
 *   #install-btn      drag-to-bookmarks-bar button (href set here)
 *   #install-steps    per-browser install instructions
 *   #demo             live demo paragraph (hover/tap tooltips)
 *   #copy-code-btn    copy-the-bookmarklet button
 *   #bookmarklet-code element holding the raw javascript: URL
 *   #tryit            "try it on this page" target
 *   #tryit-status     success indicator, lit by the ais-glossary-ready event
 *
 * This is the scaffold: it loads the built bookmarklet and points #install-btn
 * at it. The later behaviors (browser detection, demo tooltip, copy, try-it
 * success) live in this same file and are invoked from init() — there is no
 * cross-file hook, so init() stays private to the IIFE.
 */
(function () {
  "use strict";

  // The built bookmarklet — single source of truth, regenerated by
  // `node build.js`. Never hand-edit. The page embeds it in #bookmarklet-code;
  // if that placeholder is empty we fall back to fetching the built artifact.
  var BOOKMARKLET_FILE = "bookmarklet.txt";

  // The glossary term data — the same terms.json the build inlines into the
  // bookmarklet. The demo fetches it for real definitions; it's served from the
  // repo root, one level up from this script.
  var TERMS_FILE = "../terms.json";

  // This script's own URL, captured eagerly — currentScript is only valid during
  // synchronous execution (now). The fallback fetch resolves the built artifact
  // relative to this file, so it works wherever onboarding.html is served from.
  var SELF_URL = (document.currentScript && document.currentScript.src) || "";

  function byId(id) {
    return document.getElementById(id);
  }

  function bookmarkletUrl() {
    try {
      return SELF_URL ? new URL(BOOKMARKLET_FILE, SELF_URL).href : BOOKMARKLET_FILE;
    } catch (e) {
      return BOOKMARKLET_FILE;
    }
  }

  function termsUrl() {
    try {
      return SELF_URL ? new URL(TERMS_FILE, SELF_URL).href : TERMS_FILE;
    } catch (e) {
      return TERMS_FILE;
    }
  }

  // Read the bookmarklet the page already embedded, if any.
  function embeddedCode() {
    var el = byId("bookmarklet-code");
    if (!el) return "";
    var code = (el.textContent || "").trim();
    return /^javascript:/i.test(code) ? code : "";
  }

  // Fetch the built artifact when the page didn't embed it (e.g. served without
  // a build step having injected it). Resolves to "" on any failure.
  function fetchCode() {
    if (typeof fetch !== "function") return Promise.resolve("");
    return fetch(bookmarkletUrl(), { cache: "no-store" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.text();
      })
      .then(function (text) {
        var code = (text || "").trim();
        return /^javascript:/i.test(code) ? code : "";
      })
      .catch(function (err) {
        if (window.console) console.warn("[onboarding] could not load bookmarklet:", err);
        return "";
      });
  }

  // Resolve the bookmarklet code from the page, else from the built file.
  // Carries wasEmbedded so applyCode needn't re-query the DOM to decide whether
  // it still owns #bookmarklet-code's contents.
  function resolveCode() {
    var embedded = embeddedCode();
    return embedded
      ? Promise.resolve({ code: embedded, wasEmbedded: true })
      : fetchCode().then(function (code) { return { code: code, wasEmbedded: false }; });
  }

  // Point the drag-to-install button at the built javascript: URL, and make
  // sure #bookmarklet-code holds it too (so the later copy behavior has a
  // single, consistent source).
  function applyCode(code, wasEmbedded) {
    if (!code) return;
    var btn = byId("install-btn");
    if (btn) btn.setAttribute("href", code);
    var codeEl = byId("bookmarklet-code");
    if (codeEl && !wasEmbedded) codeEl.textContent = code;
  }

  // --- behavior-browser-detect: tailored install steps ----------------------

  // Identify the desktop browser from the UA string. Order matters: Edge and
  // Opera UAs also contain "Chrome", and Chrome's also contains "Safari".
  function detectBrowser() {
    var ua = navigator.userAgent || "";
    if (/\bEdg(?:e|A|iOS)?\//.test(ua)) return "edge";
    if (/\bFirefox\//.test(ua)) return "firefox";
    if (/\b(?:OPR|Opera)\//.test(ua)) return "chrome"; // Chromium-based: same flow
    if (/\bChrom(?:e|ium)\//.test(ua)) return "chrome";
    if (/\bSafari\//.test(ua) && /\bVersion\//.test(ua)) return "safari";
    return "other";
  }

  function isMac() {
    var p = (navigator.userAgentData && navigator.userAgentData.platform) ||
            navigator.platform || navigator.userAgent || "";
    return /Mac/i.test(p);
  }

  function kbd(text) {
    var k = document.createElement("kbd");
    k.textContent = text;
    return k;
  }

  // Toggle-bookmarks-bar shortcut (Chrome/Edge/Firefox share it), per platform.
  function barShortcut() {
    return isMac() ? "⌘⇧B" : "Ctrl+Shift+B";
  }

  // Ordered install steps for the detected browser. Each step is an array of
  // strings / inline nodes appended into an <li>.
  function installSteps(browser) {
    var DRAG = "Drag the “📘 AI Safety Glossary” button above onto the bar.";
    var USE = "Open any article, click the bookmark, and hover a highlighted term to read its definition.";
    switch (browser) {
      case "edge":
      case "chrome":
        return [
          ["Show the bookmarks bar — press ", kbd(barShortcut()),
           " (or menu ▸ Bookmarks ▸ Show bookmarks bar)."],
          [DRAG],
          [USE]
        ];
      case "firefox":
        return [
          ["Show the bookmarks toolbar — press ", kbd(barShortcut()),
           " (or right-click the toolbar ▸ Bookmarks Toolbar ▸ Always Show)."],
          [DRAG],
          [USE]
        ];
      case "safari":
        // Safari won't let you drag a javascript: bookmark, so edit one by hand.
        return [
          ["Show the Favourites bar — ", kbd("⌘⇧B"),
           " (View ▸ Show Favourites Bar)."],
          ["Bookmark this page with ", kbd("⌘D"), " and save it to Favourites."],
          ["Copy the code with the Copy button below, then right-click the new " +
           "bookmark ▸ Edit Address and paste the code as its address."],
          [USE]
        ];
      default:
        return [
          ["Show your browser’s bookmarks/favourites bar (often ", kbd(barShortcut()), ")."],
          [DRAG + " If your browser blocks dragging javascript: bookmarks, copy the code " +
           "below and paste it as a new bookmark’s address instead."],
          [USE]
        ];
    }
  }

  // Replace #install-steps with steps tailored to the detected browser.
  function writeInstallSteps() {
    var host = byId("install-steps");
    if (!host) return;
    var browser = detectBrowser();
    host.dataset.browser = browser; // expose for styling / QA
    var ol = document.createElement("ol");
    installSteps(browser).forEach(function (parts) {
      var li = document.createElement("li");
      parts.forEach(function (p) {
        li.appendChild(typeof p === "string" ? document.createTextNode(p) : p);
      });
      ol.appendChild(li);
    });
    host.textContent = "";
    host.appendChild(ol);
  }

  // --- behavior-copy-clipboard: copy the bookmarklet to the clipboard --------

  var COPY_IDLE = "Copy code";
  var COPY_DONE = "Copied ✓";
  var COPY_FAIL = "Press ⌘/Ctrl+C to copy";
  var copyResetTimer = null;
  var copyStatus = null; // visually-hidden live region for screen-reader feedback

  function isBookmarkletCode(text) {
    return /^javascript:/i.test((text || "").trim());
  }

  // The text the Copy button offers, read live from #bookmarklet-code so it
  // reflects whatever the build embedded or applyCode() injected. That element
  // is a <textarea>, so .value is the source of truth (textContent as fallback);
  // we only return it if it's actually a bookmarklet, matching resolveCode().
  function codeToCopy() {
    var el = byId("bookmarklet-code");
    if (!el) return "";
    var raw = typeof el.value === "string" ? el.value : (el.textContent || "");
    var code = raw.trim();
    return isBookmarkletCode(code) ? code : "";
  }

  // Copy via a throwaway textarea + execCommand — the fallback for http/older
  // browsers where the async Clipboard API is unavailable or blocked.
  function legacyCopy(text) {
    var ta = document.createElement("textarea");
    ta.value = text;
    ta.setAttribute("readonly", "");
    ta.style.position = "fixed";
    ta.style.top = "-9999px";
    document.body.appendChild(ta);
    ta.select();
    var ok = false;
    try { ok = document.execCommand("copy"); } catch (e) { ok = false; }
    document.body.removeChild(ta);
    return ok ? Promise.resolve() : Promise.reject(new Error("execCommand copy failed"));
  }

  // Write to the clipboard. Prefer the async Clipboard API (needs a user
  // gesture + secure context), else fall back. Rejects if both fail.
  function copyText(text) {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      return navigator.clipboard.writeText(text).catch(function () {
        return legacyCopy(text);
      });
    }
    return legacyCopy(text);
  }

  // Flash a transient label on the button, mirror it into the live region so
  // screen-reader users hear the result, then restore the idle label.
  function flash(btn, label) {
    btn.textContent = label;
    if (copyStatus) copyStatus.textContent = label;
    if (copyResetTimer) clearTimeout(copyResetTimer);
    copyResetTimer = setTimeout(function () {
      btn.textContent = COPY_IDLE;
      if (copyStatus) copyStatus.textContent = "";
      copyResetTimer = null;
    }, 2000);
  }

  // Wire the Copy button. The skeleton ships it hidden; we only surface it once
  // there's code to copy, so it degrades to absent when the build hasn't
  // injected the bookmarklet yet (issue #9). Returns a refresh() the caller can
  // re-run after applyCode() resolves the code asynchronously.
  function initCopyButton() {
    var btn = byId("copy-code-btn");
    if (!btn) return function () {};
    if (!(btn.textContent || "").trim()) btn.textContent = COPY_IDLE;

    // Visually-hidden status node (reuses the page's .sr-only utility) so copy
    // feedback is announced to assistive tech, not just shown in the button.
    if (!copyStatus) {
      copyStatus = document.createElement("span");
      copyStatus.className = "sr-only";
      copyStatus.setAttribute("role", "status");
      copyStatus.setAttribute("aria-live", "polite");
      (btn.parentNode || document.body).appendChild(copyStatus);
    }

    function refresh() {
      var hasCode = !!codeToCopy();
      btn.hidden = !hasCode;
      btn.disabled = !hasCode;
    }
    refresh();

    btn.addEventListener("click", function () {
      var code = codeToCopy();
      if (!code) return;
      copyText(code)
        .then(function () { flash(btn, COPY_DONE); })
        .catch(function (err) {
          if (window.console) console.warn("[onboarding] copy failed:", err);
          flash(btn, COPY_FAIL);
        });
    });

    return refresh;
  }

  // --- behavior-demo-tooltip: hover/focus/tap definitions for #demo terms -----
  //
  // The #demo paragraph ships pre-marked .glossary-term spans (styled by
  // widget-styles.css). This reproduces the real widget's tooltip on them —
  // fetching the canonical terms.json for definitions and reusing the widget's
  // .glossary-tip / .glossary-src classes so the demo looks identical — without
  // running the bookmarklet itself (its IIFE would annotate the whole page and
  // toast). Degrades to plain highlighted terms if terms.json can't be loaded.

  // Fetch and parse the term list. Resolves to [] on any failure.
  function fetchTerms() {
    if (typeof fetch !== "function") return Promise.resolve([]);
    return fetch(termsUrl(), { cache: "no-store" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(function (data) { return (data && data.terms) || []; })
      .catch(function (err) {
        if (window.console) console.warn("[onboarding] could not load terms:", err);
        return [];
      });
  }

  // Map every term and alias (lower-cased) to its entry.
  function indexTerms(terms) {
    var map = {};
    terms.forEach(function (entry) {
      if (!entry || !entry.term || !entry.definition) return;
      [entry.term].concat(entry.aliases || []).forEach(function (name) {
        if (name) map[String(name).toLowerCase()] = entry;
      });
    });
    return map;
  }

  function safeExternalUrl(raw) {
    if (!raw) return "";
    try {
      var u = new URL(String(raw), window.location.href);
      return (u.protocol === "http:" || u.protocol === "https:") ? u.href : "";
    } catch (e) {
      return "";
    }
  }

  // Attach the definition/source to a demo span so the tooltip can read it,
  // mirroring the data the widget's makeTermSpan() sets (incl. aria-label).
  function annotateDemoTerm(span, entry) {
    var label = entry.term + ": " + entry.definition;
    span.dataset.definition = entry.definition;
    if (entry.source) {
      span.dataset.sourceName = entry.source.name || entry.source.url || "";
      span.dataset.sourceUrl = entry.source.url || "";
      if (span.dataset.sourceName) label += " (Source: " + span.dataset.sourceName + ")";
    }
    span.setAttribute("aria-label", label);
    if (!span.hasAttribute("tabindex")) span.tabIndex = 0;
  }

  var demoTip = null, demoHideTimer = null;

  function cancelDemoHide() { if (demoHideTimer) { clearTimeout(demoHideTimer); demoHideTimer = null; } }
  function scheduleDemoHide() { cancelDemoHide(); demoHideTimer = setTimeout(hideDemoTip, 250); }
  function hideDemoTip() { cancelDemoHide(); if (demoTip) demoTip.hidden = true; }

  function ensureDemoTip() {
    if (demoTip) return;
    demoTip = document.createElement("span");
    demoTip.className = "glossary-tip";
    demoTip.setAttribute("role", "tooltip");
    demoTip.hidden = true;
    demoTip.addEventListener("mouseenter", cancelDemoHide);
    demoTip.addEventListener("mouseleave", scheduleDemoHide);
    document.body.appendChild(demoTip);
  }

  // Place the fixed-position tip below the term, flipping above / clamping to the
  // viewport when it would overflow — matching the widget's placement.
  function positionDemoTip(el) {
    var r = el.getBoundingClientRect();
    var gap = 6, margin = 8;
    var w = demoTip.offsetWidth, h = demoTip.offsetHeight;
    var vw = document.documentElement.clientWidth, vh = window.innerHeight;
    var flipUp = (r.bottom + gap + h > vh) && (r.top - gap - h >= 0);
    var top = flipUp ? (r.top - gap - h) : (r.bottom + gap);
    top = Math.max(margin, Math.min(top, vh - h - margin));
    var left = Math.max(margin, Math.min(r.left, vw - w - margin));
    demoTip.style.top = top + "px";
    demoTip.style.left = left + "px";
  }

  function showDemoTip(el) {
    if (!el.dataset.definition) return;
    ensureDemoTip();
    cancelDemoHide();
    while (demoTip.firstChild) demoTip.removeChild(demoTip.firstChild);
    demoTip.appendChild(document.createTextNode(el.dataset.definition));
    if (el.dataset.sourceUrl || el.dataset.sourceName) {
      var src = document.createElement("span");
      src.className = "glossary-src";
      src.appendChild(document.createTextNode("Source: "));
      var safe = safeExternalUrl(el.dataset.sourceUrl);
      if (safe) {
        var a = document.createElement("a");
        a.href = safe;
        a.textContent = el.dataset.sourceName || safe;
        a.target = "_blank";
        a.rel = "noopener noreferrer";
        src.appendChild(a);
      } else {
        src.appendChild(document.createTextNode(el.dataset.sourceName || ""));
      }
      demoTip.appendChild(src);
    }
    demoTip.hidden = false;
    positionDemoTip(el);
  }

  // Wire definitions + tooltip interactions onto the #demo terms.
  function wireDemoTooltips() {
    var demo = byId("demo");
    if (!demo) return;
    var spans = demo.querySelectorAll(".glossary-term");
    if (!spans.length) return;

    fetchTerms().then(function (terms) {
      var map = indexTerms(terms);
      var wired = 0;
      Array.prototype.forEach.call(spans, function (span) {
        var entry = map[(span.textContent || "").replace(/\s+/g, " ").trim().toLowerCase()];
        if (entry) { annotateDemoTerm(span, entry); wired++; }
      });
      if (!wired) return; // nothing matched; leave terms as plain highlights

      var hit = function (e) { return e.target.closest && e.target.closest(".glossary-term"); };
      demo.addEventListener("mouseover", function (e) { var el = hit(e); if (el) showDemoTip(el); });
      demo.addEventListener("mouseout", function (e) { if (hit(e)) scheduleDemoHide(); });
      demo.addEventListener("focusin", function (e) { var el = hit(e); if (el) showDemoTip(el); });
      demo.addEventListener("focusout", function (e) {
        if (e.relatedTarget && demoTip && demoTip.contains(e.relatedTarget)) return;
        scheduleDemoHide();
      });
      demo.addEventListener("click", function (e) { var el = hit(e); if (el) showDemoTip(el); }); // tap
      document.addEventListener("click", function (e) {
        var t = e.target;
        var inside = t.closest && (t.closest(".glossary-term") || t.closest(".glossary-tip"));
        if (demoTip && !demoTip.hidden && !inside) hideDemoTip();
      });
      document.addEventListener("keydown", function (e) { if (e.key === "Escape") hideDemoTip(); });
      window.addEventListener("scroll", hideDemoTip, { passive: true });
    });
  }

  function init() {
    writeInstallSteps();
    wireDemoTooltips();
    var refreshCopy = initCopyButton();
    resolveCode()
      .then(function (r) {
        applyCode(r.code, r.wasEmbedded);
        refreshCopy(); // code may have just been injected into #bookmarklet-code
      })
      .catch(function (err) {
        if (window.console) console.warn("[onboarding] init failed:", err);
      });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
