/*
 * AI Safety Glossary — onboarding page behaviors.
 *
 * Progressive enhancement for the desktop-only install/onboarding page. The
 * page markup is owned by onboarding.html; this script only wires behavior onto
 * the shared-contract element IDs:
 *
 *   #install-btn      drag-to-bookmarks-bar button (href set here)
 *   #install-steps    per-browser install instructions
 *   #demo             live demo paragraph (hover/tap tooltips)
 *   #copy-code-btn    copy-the-bookmarklet button
 *   #bookmarklet-code element holding the raw javascript: URL
 *   #tryit            "try it on this page" target
 *   #tryit-status     success indicator, lit by the ais-glossary-ready event
 *
 * This is the scaffold: it loads the built bookmarklet and points #install-btn
 * at it. The later behaviors (browser detection, demo tooltip, copy, try-it
 * success) live in this same file and are invoked from init() — there is no
 * cross-file hook, so init() stays private to the IIFE.
 */
(function () {
  "use strict";

  // The built bookmarklet — single source of truth, regenerated by
  // `node build.js`. Never hand-edit. The page embeds it in #bookmarklet-code;
  // if that placeholder is empty we fall back to fetching the built artifact.
  var BOOKMARKLET_FILE = "bookmarklet.txt";

  // This script's own URL, captured eagerly — currentScript is only valid during
  // synchronous execution (now). The fallback fetch resolves the built artifact
  // relative to this file, so it works wherever onboarding.html is served from.
  var SELF_URL = (document.currentScript && document.currentScript.src) || "";

  function byId(id) {
    return document.getElementById(id);
  }

  function bookmarkletUrl() {
    try {
      return SELF_URL ? new URL(BOOKMARKLET_FILE, SELF_URL).href : BOOKMARKLET_FILE;
    } catch (e) {
      return BOOKMARKLET_FILE;
    }
  }

  // Read the bookmarklet the page already embedded, if any.
  function embeddedCode() {
    var el = byId("bookmarklet-code");
    if (!el) return "";
    var code = (el.textContent || "").trim();
    return /^javascript:/i.test(code) ? code : "";
  }

  // Fetch the built artifact when the page didn't embed it (e.g. served without
  // a build step having injected it). Resolves to "" on any failure.
  function fetchCode() {
    if (typeof fetch !== "function") return Promise.resolve("");
    return fetch(bookmarkletUrl(), { cache: "no-store" })
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.text();
      })
      .then(function (text) {
        var code = (text || "").trim();
        return /^javascript:/i.test(code) ? code : "";
      })
      .catch(function (err) {
        if (window.console) console.warn("[onboarding] could not load bookmarklet:", err);
        return "";
      });
  }

  // Resolve the bookmarklet code from the page, else from the built file.
  // Carries wasEmbedded so applyCode needn't re-query the DOM to decide whether
  // it still owns #bookmarklet-code's contents.
  function resolveCode() {
    var embedded = embeddedCode();
    return embedded
      ? Promise.resolve({ code: embedded, wasEmbedded: true })
      : fetchCode().then(function (code) { return { code: code, wasEmbedded: false }; });
  }

  // Point the drag-to-install button at the built javascript: URL, and make
  // sure #bookmarklet-code holds it too (so the later copy behavior has a
  // single, consistent source).
  function applyCode(code, wasEmbedded) {
    if (!code) return;
    var btn = byId("install-btn");
    if (btn) btn.setAttribute("href", code);
    var codeEl = byId("bookmarklet-code");
    if (codeEl && !wasEmbedded) codeEl.textContent = code;
  }

  function init() {
    resolveCode()
      .then(function (r) { applyCode(r.code, r.wasEmbedded); })
      .catch(function (err) {
        if (window.console) console.warn("[onboarding] init failed:", err);
      });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
